services:
  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
    tty: true
  rouletteapi:
    depends_on:
      - "redis"
    build: .
    ports:
      - "5000:5000"